apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pbcldm7d6-java-springboot
  janus-idp.io/tekton: pbcldm7d6-java-springboot
  backstage.io/kubernetes-id: pbcldm7d6-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pbcldm7d6-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
